app:
  name: video
  domain: emmed.ee
  pullpolicy: Always # IfNotPresent # set to Always for auto updates

auth:
  enabled: true
  guests: false
  # internal auth
  type: internal
  admin:
    user: admin
    password: "jitsiadmin"
  # ldap auth - remove above "type: internal" auth to use it
  #type: ldap
  #ldapauthmethod: bind
  #ldapurl: ldap://LDAP_SERVER
  #ldapusetls: 1
  #ldapstarttls: 1 # needs LDAP_VERSIOn 3
  #ldaptlscacertfile:
  #ldaptlscacertdir:
  #ldaptlscheckpeer:
  #ldapbase: OU=users,DC=domain,DC=local
  #ldapbinddn: CN=ldap user,OU=svc_users,DC=domain,DC=local
  #ldapbindpw: VerySecretPassword
  #ldapfilter: (&(&(|(objectclass=person)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))
  #ldapversion: 3 # can break helm upgrade

logLevel: "info"
hideWelcomePage: true
# Remove following # to use different stun servers
# stun:
#  server: stun.stunprotocol.org:3478, stun.services.mozilla.com:3478
